// Generated by Unloop
// Smart Washing Machine

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_start_cycle_clicked(|| {
        println!("start_cycle clicked");
    });
    
    app.on_pause_clicked(|| {
        println!("pause clicked");
    });
    
    app.on_add_time_clicked(|| {
        println!("add_time clicked");
    });
    

    
    app.run()
}
