// Generated Data Model

export struct AppData {
    time-remaining: float,
    load-weight: float,
    water-temp: float,
    door-status: string,
    water-status: string,
    drain-status: string,
    spin-speed: float,
    target-spin-speed: float,
    default-cycle: string,
    water-temp-pref: string,
    auto-detergent: bool,
    cycle-complete-beep: bool,
    door-open-alert: bool,
    maintenance-reminders: bool,
    brightness: float,
    sleep-timer: float,
    model-number: string,
    firmware-version: string,
}
